### ISSUE TITLE
Support aiohttp middlewares

### ISSUE THREAD

**Issue by Kaveshnikov** [mosquito/aiohttp-asgi#1]
Hi! Are you going to support aiohttp middlewares? 
I tried to use this lib with aiohttp.web.normalize_path_middleware() and got an exception: `ASGIMatchInfo' object has no attribute 'set_current_app'`. This happened because of [this call](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_middlewares.py#L122). 

aiohttp==3.6.2
aiohttp-asgi==0.2.0

**Comment by mosquito** [comment]
It’s version 0.2.0, feel free for contribute your changes and proposals.
