### ISSUE TITLE
Wrong __iter__() implementation

### ISSUE THREAD

**Issue by Kaveshnikov** [mosquito/aiohttp-asgi#3]
HI! According to [pep234](https://www.python.org/dev/peps/pep-0234/) `__iter__()` must return an iterator object. This method raises `StopIteration` in the `ASGIResource` class. It breaks calls like `app.router.routes`. @mosquito I can make a PR to fix it, if you don't mind.

**Comment by mosquito** [comment]
Feel free to make a PR

**Comment by Kaveshnikov** [comment]
When is the next release with fixes expected?

**Comment by mosquito** [comment]
0.3.1 has been released

**Comment by mosquito** [comment]
@Kaveshnikov BTW sorry for delay, I had lost email notification
