### ISSUE TITLE
Race with aiohttp main cycle

### ISSUE THREAD

**Issue by PaulWasTaken** [mosquito/aiohttp-asgi#6]
Greetings,
I have a question. 

`aiohttp=3.6.2, aiohttp_asgi=0.3.1`

When I try to send a certain piece of data >170 Kb, I get a lot of errors like 
```
line 78, in _drain_helper    
   assert waiter is None or waiter.cancelled()
```
I've done a little and hopefully correct investigation, and it looks like `ASGIContext` should consider the `get_response` method to have completed recently. 

The current behaviour is as follows:
1) Set `start_response_event` to https://github.com/mosquito/aiohttp-asgi/blob/master/aiohttp_asgi/resource.py#L204.
2) On https://github.com/mosquito/aiohttp-asgi/blob/master/aiohttp_asgi/resource.py#L263, the method is considered completed
3) On https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web_protocol.py#L418, a loop is started
4) On https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web_protocol.py#L462 another `write` + `drain` is called. 

Currently, aiohttp doesn't wait until we've sent all our data.

However, I'm not sure if I'm using the library correctly. Could you please confirm or refute my assumptions. If I'm wrong somewhere, how should I proceed in my case?

To reproduce:
```
async def f(scope, receive, send):
            if payload.get("type") == "http.request":
                data = 'a' * 65600 * 1024

                await send(
                    {
                        "type": "http.response.start",
                        "status": 200,
                        "headers": []
                    }
                )

                await send({"type": "http.response.body", "body": data.encode()})

new_res = aiohttp_asgi.ASGIResource(f, root_path='/test')
app.router.register_resource(new_res)
```

**Comment by PaulWasTaken** [comment]
Bump

**Comment by PaulWasTaken** [comment]
@mosquito

**Comment by mosquito** [comment]
I didn't quite understand your case, but the test written according to your example works.

**Comment by PaulWasTaken** [comment]
https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/base_protocol.py#L78 this assertion fails.

If I understand correctly, we should wait until the asgi resource finishes writing

**Comment by mosquito** [comment]
@PaulWasTaken I will be very happy to fix your problem if we can write code that will reproduce it in the test. Then it will be a guarantee that it will not happen again.

**Comment by mosquito** [comment]
I tried to [fix it "blindly" here](https://github.com/mosquito/aiohttp-asgi/commit/4172c0f870ae9cd822cd608af41f73059587798e), try it on version 0.3.2.

**Comment by PaulWasTaken** [comment]
Take a look at this modification

```
@pytest.mark.asyncio
async def test_basic(mocker, client):
    raised = False

    class TestStreamResponse(StreamResponse):
        async def write_eof(self, data: bytes=b'') -> None:
            nonlocal raised

            try:
                await super().write_eof(data=data)
            except AssertionError:
                raised = True
                raise

    mocker.patch('aiohttp_asgi.resource.StreamResponse', TestStreamResponse)

    async with client.get("/") as response:
        response.raise_for_status()
        body = await response.read()
        assert body

    assert not raised
```

**Comment by PaulWasTaken** [comment]
```
async def get_response(self) -> t.Union[StreamResponse, WebSocketResponse]:
    await self.app(
        self.scope,
        self.on_receive,
        self.on_send,
    )

    if self.response is None:
        raise RuntimeError

    return self.response
```
This modification solves the problem.
If I understand correctly, we were returning `self.response` even though it was not populated with data yet

**Comment by PaulWasTaken** [comment]
@mosquito I will open PR, if you agree

**Comment by mosquito** [comment]
Of course, feel free.
